### ISSUE TITLE
Suggestions on the current UI

### ISSUE THREAD

**Issue by LittleAprilFool** [ETH-PEACH-Lab/collaborative-learning-extension-jupyter#1]
1. Add more instructions for the code exercise

<img width="1150" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/67e2ca12-5f6c-4fe7-a266-2f5b7e8ddf5b">

<img width="1173" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/b6aa9481-f483-4b0c-9b6a-8c60228e5184">

**Comment by LittleAprilFool** [comment]
2. Scrolling doesn't work when the user is focusing on a code editor

<img width="1173" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/1fef0f0c-879b-4a5f-bd81-de8f6d52c965">

**Comment by LittleAprilFool** [comment]
3. Action buttons for assertion code

<img width="1176" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/2b36d434-e891-46cf-a050-6431f441fd79">

The action buttons with assertion code are currently placed outside of the assertion code box. Users may misunderstand them with actions on the exercise --- e.g., deleting an exercise instead of deleting an assertion

**Comment by LittleAprilFool** [comment]
4. For MCQs, the button to add options should be more obvious.
<img width="1164" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/ef2b494c-fdb7-4947-b5e6-5b3f6204f7a1">

An example fix:
<img width="1177" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/e2224b4e-e513-4915-b97a-a2d77b107510">

**Comment by LittleAprilFool** [comment]
5. Rendering doesn't work after switching to the learners' view?
<img width="1187" alt="image" src="https://github.com/ETH-PEACH-Lab/collaborative-learning-extension-jupyter/assets/5129786/d790e8f7-f293-4496-8fa9-2ec9438b9c88">

**Comment by pascallinder** [comment]
Thanks for the suggestions. I hadn't seen them until now. I'll consider them after today's lab meeting.
The point 5: not rendering after switching back, should already be fixed.
